export default [
  {
    id: 1,
    team: "Georgia State",
    where: "Home",
    date: "Sat Sep 3",
    time: "7:30 PM",
  },
  {
    id: 2,
    team: "Arkansas",
    where: "Away",
    date: "Sat Sep 10",
    time: "12:00 PM",
  },
  {
    id: 3,
    team: "Georgia",
    where: "Home",
    date: "Sat Sep 17",
    time: "12:00 PM",
  },
  {
    id: 4,
    team: "Charlotte",
    where: "Home",
    date: "Sat Sep 24",
    time: "TBA",
  },
  {
    id: 5,
    team: "South Carolina State",
    where: "Home",
    date: "Sat Oct 1",
    time: "TBA",
  },
  {
    id: 6,
    team: "Kentucky",
    where: "Away",
    date: "Sat Oct 8",
    time: "TBA",
  },
  {
    id: 7,
    team: "Texas A&M",
    where: "Home",
    date: "Sat Oct 22",
    time: "TBA",
  },
  {
    id: 8,
    team: "Missouri",
    where: "Home",
    date: "Sat Oct 29",
    time: "TBA",
  },
  {
    id: 9,
    team: "Vanderbilt",
    where: "Away",
    date: "Sat Nov 5",
    time: "TBA",
  },
  {
    id: 10,
    team: "Florida",
    where: "Away",
    date: "Sat Nov 12",
    time: "TBA",
  },
  {
    id: 11,
    team: "Tennessee",
    where: "Home",
    date: "Sat Nov 19",
    time: "TBA",
  },
  {
    id: 12,
    team: "Clemson",
    where: "Away",
    date: "Sat Nov 26",
    time: "TBA",
  },
];
